name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          # If you have requirements files in future, this will install them.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Ensure common test/lint/security tools are available
          pip install --upgrade pytest flake8 bandit

      - name: Lint (flake8)
        # adjust --max-line-length or add config file if you prefer
        run: |
          # If you don't want lint failures to block CI initially, you can add "|| true"
          flake8 . --max-line-length=88

      - name: Security scan (bandit)
        run: |
          # Recursively scan repository for Python security issues
          bandit -r . -q -lll

      - name: Run tests (pytest)
        env:
          FLASK_ENV: testing
        run: |
          pytest -q
