# .github/workflows/bandit_scan.yml
name: Bandit SAST Scan
on:
push:
branches:
- main
pull_request:
branches:
- main
jobs:
bandit_scan:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v4
- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.x'
- name: Install Bandit
run: pip install bandit
- name: Run Bandit Scan
run: bandit -r . -f json -o bandit-results.json || true # Run bandit, output to JSON, '|| true' to
not fail workflow immediately
- name: Upload Bandit Results
uses: actions/upload-artifact@v4
with:
name: bandit-results
path: bandit-results.json
